version: "3.9"

services:
  backend:
    build:
      context: ./upload_photo_backend
      dockerfile: Dockerfile
    container_name: upload_photo_backend
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000
             python -m celery -A upload_photo_backend worker -l info"
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./upload_photo_backend:/app
    ports:
      - 127.0.0.1:8000:8000
    networks:
      - upload_photo
    depends_on:
      - db
      - cache

  frontend:
    build:
      context: ./upload_photo_frontend
      dockerfile: Dockerfile
    container_name: upload_photo_frontend
    command: npm run dev
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./upload_photo_frontend:/app
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - upload_photo
    depends_on:
      - backend


  db:
    image: postgres:15-alpine3.17
    container_name: upload_photo_database
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: on-failure
    ports:
      - 127.0.0.1:5433:5432
    networks:
      - upload_photo
    volumes:
      - postgres_data_upload_photo:/var/lib/postgresql/data

  cache:
    image: redis:7.0-alpine3.17
    container_name: redis
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - upload_photo

networks:
  upload_photo:
    driver: bridge

volumes:
  postgres_data_upload_photo:
