# Generated by Django 4.1.6 on 2023-02-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeaccount',
            name='binary_link',
        ),
        migrations.AddField(
            model_name='sizeimage',
            name='binary_link',
            field=models.BooleanField(default=False),
        ),
    ]
