# Generated by Django 4.1.6 on 2023-02-20 16:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeimage',
            name='expiring_time',
        ),
        migrations.AddField(
            model_name='sizeimage',
            name='originally',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BinaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiring_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)])),
                ('image_binary', models.BinaryField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binary', to='main.image')),
            ],
        ),
    ]
