# Generated by Django 4.1.6 on 2023-02-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_sizeimage_expiring_time_sizeimage_originally_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeimage',
            name='binary_link',
        ),
        migrations.RemoveField(
            model_name='sizeimage',
            name='originally',
        ),
        migrations.AddField(
            model_name='typeaccount',
            name='binary_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeaccount',
            name='originally',
            field=models.BooleanField(default=False),
        ),
    ]
