# Generated by Django 4.1.6 on 2023-02-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_typeaccount_binary_link_sizeimage_binary_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='test',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
