# Generated by Django 4.1.6 on 2023-02-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_image_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='test',
        ),
    ]
