# Generated by Django 4.1.6 on 2023-02-18 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_image_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='sizeimage',
            old_name='length',
            new_name='height',
        ),
        migrations.AddField(
            model_name='sizeimage',
            name='expiring_time',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
            preserve_default=False,
        ),
    ]
