# Generated by Django 4.1.6 on 2023-03-04 18:35

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_image_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binaryimage',
            name='expiring_time',
        ),
        migrations.AddField(
            model_name='binaryimage',
            name='expired',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
