# Generated by Django 4.1.6 on 2023-02-18 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_image_user_alter_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
