# Generated by Django 4.1.6 on 2023-03-10 19:00

from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_binaryimage_expiring_time_binaryimage_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(null=True, upload_to=main.utils.uniq_path_original_image),
        ),
        migrations.CreateModel(
            name='SizeImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main.utils.uniq_path_new_size_image)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='different_picture_sizes', to='main.image')),
            ],
        ),
    ]
